version: "2"

services:
  web:
    build: ./app
    container_name: app
    depends_on:
      - grafana
      - influxdb
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana
    environment:
      GF_SERVER_HTTP_PORT: 3030
      GF_INSTALL_PLUGINS: https://github.com/cloudspout/cloudspout-button-panel/releases/download/7.0.2/cloudspout-button-panel.zip;cloudspout-button-panel
    container_name: grafana
    restart: always
    ports:
      - 3030:3030
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  influxdb:
    image: influxdb:1.8
    environment:
      INFLUXDB_DB: vt
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: supersecretpassword
      INFLUXDB_USER: telegraf
      INFLUXDB_USER_PASSWORD: secretpassword
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influxdb-volume:/var/lib/influxdb

volumes:
  influxdb-volume:
    external: false