{
 "title": "Verified Telemetry",
 "time": { "from": "now-1m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DeviceName",
    "query": "SHOW TAG VALUES WITH KEY = \"deviceId\""
   }
  ]
 },
 "panels": [
  { "title": "Verified Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Device Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "property_messages",
     "query": "SELECT \"jsonvalue\" FROM \"property_messages\" WHERE (\"deviceId\" =~ /^$DeviceName$/ AND \"componentName\" = 'vTDevice' AND \"property\" = 'deviceStatus')",
     "select": [
      [
       { "params": [ "jsonvalue" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "property", "operator": "=", "value": "deviceStatus" }
     ]
    }
   ]
  },
  {
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Verified Telemetry",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "property_messages",
     "query": "SELECT \"jsonvalue\" FROM \"property_messages\" WHERE (\"deviceId\" =~ /^$DeviceName$/ AND \"componentName\" = 'vTDevice' AND \"property\" = 'enableVerifiedTelemetry') ",
     "select": [
      [
       { "params": [ "jsonvalue" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$DeviceName$/" },
      { "condition": "AND", "key": "property", "operator": "=", "value": "enableVerifiedTelemetry" }
     ]
    }
   ]
  },
  {
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Soil Moisture 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Working",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "telemetry_messages",
     "select": [
      [
       { "params": [ "jsonasnumber" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$DeviceName$/" },
      { "condition": "AND", "key": "componentName", "operator": "=", "value": "sampleDevice" },
      { "condition": "AND", "key": "telemetry", "operator": "=", "value": "soilMoistureExternal1" },
      { "condition": "AND", "key": "verifiedTelemetryStatus", "operator": "=", "value": "true" }
     ]
    },
    {
     "alias": "Fault",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "telemetry_messages",
     "select": [
      [
       { "params": [ "jsonasnumber" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$DeviceName$/" },
      { "condition": "AND", "key": "componentName", "operator": "=", "value": "sampleDevice" },
      { "condition": "AND", "key": "telemetry", "operator": "=", "value": "soilMoistureExternal1" },
      { "condition": "AND", "key": "verifiedTelemetryStatus", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "verifiedTelemetrySupport", "operator": "=", "value": "true" }
     ]
    },
    {
     "alias": "Unverified",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "telemetry_messages",
     "select": [
      [
       { "params": [ "jsonasnumber" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$DeviceName$/" },
      { "condition": "AND", "key": "componentName", "operator": "=", "value": "sampleDevice" },
      { "condition": "AND", "key": "telemetry", "operator": "=", "value": "soilMoistureExternal1" },
      { "condition": "AND", "key": "verifiedTelemetrySupport", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "verifiedTelemetryStatus", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Soil Moisture 2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Working",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "telemetry_messages",
     "select": [
      [
       { "params": [ "jsonasnumber" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$DeviceName$/" },
      { "condition": "AND", "key": "componentName", "operator": "=", "value": "sampleDevice" },
      { "condition": "AND", "key": "telemetry", "operator": "=", "value": "soilMoistureExternal2" },
      { "condition": "AND", "key": "verifiedTelemetryStatus", "operator": "=", "value": "true" }
     ]
    },
    {
     "alias": "Fault",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "telemetry_messages",
     "select": [
      [
       { "params": [ "jsonasnumber" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$DeviceName$/" },
      { "condition": "AND", "key": "componentName", "operator": "=", "value": "sampleDevice" },
      { "condition": "AND", "key": "telemetry", "operator": "=", "value": "soilMoistureExternal2" },
      { "condition": "AND", "key": "verifiedTelemetryStatus", "operator": "=", "value": "false" }
     ]
    },
    {
     "alias": "Unverified",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "telemetry_messages",
     "select": [
      [
       { "params": [ "jsonasnumber" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$DeviceName$/" },
      { "condition": "AND", "key": "componentName", "operator": "=", "value": "sampleDevice" },
      { "condition": "AND", "key": "telemetry", "operator": "=", "value": "soilMoistureExternal2" },
      { "condition": "AND", "key": "verifiedTelemetrySupport", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "verifiedTelemetryStatus", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Command",
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Command",
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Unverified",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "telemetry_messages",
     "select": [
      [
       { "params": [ "jsonasnumber" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$DeviceName$/" },
      { "condition": "AND", "key": "componentName", "operator": "=", "value": "sampleDevice" },
      { "condition": "AND", "key": "telemetry", "operator": "=", "value": "humidityPercentage" },
      { "condition": "AND", "key": "verifiedTelemetrySupport", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Magnetic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Unverified",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "telemetry_messages",
     "select": [
      [
       { "params": [ "jsonasnumber" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$DeviceName$/" },
      { "condition": "AND", "key": "componentName", "operator": "=", "value": "sampleDevice" },
      { "condition": "AND", "key": "telemetry", "operator": "=", "value": "magnetic" },
      { "condition": "AND", "key": "verifiedTelemetrySupport", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Unverified",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "telemetry_messages",
     "select": [
      [
       { "params": [ "jsonasnumber" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$DeviceName$/" },
      { "condition": "AND", "key": "componentName", "operator": "=", "value": "sampleDevice" },
      { "condition": "AND", "key": "telemetry", "operator": "=", "value": "pressure" },
      { "condition": "AND", "key": "verifiedTelemetrySupport", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Unverified",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "telemetry_messages",
     "select": [
      [
       { "params": [ "jsonasnumber" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$DeviceName$/" },
      { "condition": "AND", "key": "componentName", "operator": "=", "value": "sampleDevice" },
      { "condition": "AND", "key": "telemetry", "operator": "=", "value": "temperature" },
      { "condition": "AND", "key": "verifiedTelemetrySupport", "operator": "=", "value": "false" }
     ]
    }
   ]
  }
 ]
}